name: ScLoad
main: me.fromgate.scload.ScLoad
version: 0.2
depend: [WorldEdit]
author: [fromgate, Exemplive]
commands:
   scload:
      aliases: [scl]
      description: ScLoad command
      usage: |
           /scload load <filename>
           /scload load <filename> <world>
           /scload reload
           /scload cfg
