name: BetterScLoad
main: br.com.finalcraft.betterscload.BetterScLoad
version: 0.2.1a
depend: [WorldEdit]
author: [EverNife]
commands:
   betterscload:
      description: BetterScLoad Main Command
      usage: /<command>
      aliases: [scload, bscl, scl]
